// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3DeliveryService.proto

package grpc.foodaid.Deliver;

public interface DeliveryPlanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.delivery.DeliveryPlan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * count of orders
   * </pre>
   *
   * <code>int32 total_deliveries = 1;</code>
   * @return The totalDeliveries.
   */
  int getTotalDeliveries();

  /**
   * <pre>
   * assigned agent
   * </pre>
   *
   * <code>string delivery_agent = 2;</code>
   * @return The deliveryAgent.
   */
  java.lang.String getDeliveryAgent();
  /**
   * <pre>
   * assigned agent
   * </pre>
   *
   * <code>string delivery_agent = 2;</code>
   * @return The bytes for deliveryAgent.
   */
  com.google.protobuf.ByteString
      getDeliveryAgentBytes();

  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @return A list containing the route.
   */
  java.util.List<java.lang.String>
      getRouteList();
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @return The count of route.
   */
  int getRouteCount();
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @param index The index of the element to return.
   * @return The route at the given index.
   */
  java.lang.String getRoute(int index);
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the route at the given index.
   */
  com.google.protobuf.ByteString
      getRouteBytes(int index);

  /**
   * <pre>
   * Add this if you want to return the orders
   * </pre>
   *
   * <code>repeated .foodaid.delivery.DeliveryOrder orders = 4;</code>
   */
  java.util.List<grpc.foodaid.Deliver.DeliveryOrder> 
      getOrdersList();
  /**
   * <pre>
   * Add this if you want to return the orders
   * </pre>
   *
   * <code>repeated .foodaid.delivery.DeliveryOrder orders = 4;</code>
   */
  grpc.foodaid.Deliver.DeliveryOrder getOrders(int index);
  /**
   * <pre>
   * Add this if you want to return the orders
   * </pre>
   *
   * <code>repeated .foodaid.delivery.DeliveryOrder orders = 4;</code>
   */
  int getOrdersCount();
  /**
   * <pre>
   * Add this if you want to return the orders
   * </pre>
   *
   * <code>repeated .foodaid.delivery.DeliveryOrder orders = 4;</code>
   */
  java.util.List<? extends grpc.foodaid.Deliver.DeliveryOrderOrBuilder> 
      getOrdersOrBuilderList();
  /**
   * <pre>
   * Add this if you want to return the orders
   * </pre>
   *
   * <code>repeated .foodaid.delivery.DeliveryOrder orders = 4;</code>
   */
  grpc.foodaid.Deliver.DeliveryOrderOrBuilder getOrdersOrBuilder(
      int index);

  /**
   * <pre>
   * Add this for a status message
   * </pre>
   *
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * Add this for a status message
   * </pre>
   *
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
