// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S3DeliveryService.proto

package grpc.foodaid.Deliver;

/**
 * Protobuf type {@code foodaid.delivery.DeliveryPlan}
 */
public final class DeliveryPlan extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodaid.delivery.DeliveryPlan)
    DeliveryPlanOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeliveryPlan.newBuilder() to construct.
  private DeliveryPlan(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeliveryPlan() {
    deliveryAgent_ = "";
    route_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeliveryPlan();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeliveryPlan(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            totalDeliveries_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deliveryAgent_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              route_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            route_.add(s);
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        route_ = route_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foodaid.Deliver.FoodaidImpl.internal_static_foodaid_delivery_DeliveryPlan_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foodaid.Deliver.FoodaidImpl.internal_static_foodaid_delivery_DeliveryPlan_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foodaid.Deliver.DeliveryPlan.class, grpc.foodaid.Deliver.DeliveryPlan.Builder.class);
  }

  public static final int TOTAL_DELIVERIES_FIELD_NUMBER = 1;
  private int totalDeliveries_;
  /**
   * <pre>
   * count of orders
   * </pre>
   *
   * <code>int32 total_deliveries = 1;</code>
   * @return The totalDeliveries.
   */
  @java.lang.Override
  public int getTotalDeliveries() {
    return totalDeliveries_;
  }

  public static final int DELIVERY_AGENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object deliveryAgent_;
  /**
   * <pre>
   * assigned agent
   * </pre>
   *
   * <code>string delivery_agent = 2;</code>
   * @return The deliveryAgent.
   */
  @java.lang.Override
  public java.lang.String getDeliveryAgent() {
    java.lang.Object ref = deliveryAgent_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deliveryAgent_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * assigned agent
   * </pre>
   *
   * <code>string delivery_agent = 2;</code>
   * @return The bytes for deliveryAgent.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeliveryAgentBytes() {
    java.lang.Object ref = deliveryAgent_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deliveryAgent_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROUTE_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList route_;
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @return A list containing the route.
   */
  public com.google.protobuf.ProtocolStringList
      getRouteList() {
    return route_;
  }
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @return The count of route.
   */
  public int getRouteCount() {
    return route_.size();
  }
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @param index The index of the element to return.
   * @return The route at the given index.
   */
  public java.lang.String getRoute(int index) {
    return route_.get(index);
  }
  /**
   * <pre>
   * ordered list of addresses
   * </pre>
   *
   * <code>repeated string route = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the route at the given index.
   */
  public com.google.protobuf.ByteString
      getRouteBytes(int index) {
    return route_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalDeliveries_ != 0) {
      output.writeInt32(1, totalDeliveries_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deliveryAgent_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deliveryAgent_);
    }
    for (int i = 0; i < route_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, route_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalDeliveries_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, totalDeliveries_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deliveryAgent_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deliveryAgent_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < route_.size(); i++) {
        dataSize += computeStringSizeNoTag(route_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRouteList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foodaid.Deliver.DeliveryPlan)) {
      return super.equals(obj);
    }
    grpc.foodaid.Deliver.DeliveryPlan other = (grpc.foodaid.Deliver.DeliveryPlan) obj;

    if (getTotalDeliveries()
        != other.getTotalDeliveries()) return false;
    if (!getDeliveryAgent()
        .equals(other.getDeliveryAgent())) return false;
    if (!getRouteList()
        .equals(other.getRouteList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_DELIVERIES_FIELD_NUMBER;
    hash = (53 * hash) + getTotalDeliveries();
    hash = (37 * hash) + DELIVERY_AGENT_FIELD_NUMBER;
    hash = (53 * hash) + getDeliveryAgent().hashCode();
    if (getRouteCount() > 0) {
      hash = (37 * hash) + ROUTE_FIELD_NUMBER;
      hash = (53 * hash) + getRouteList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Deliver.DeliveryPlan parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foodaid.Deliver.DeliveryPlan prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodaid.delivery.DeliveryPlan}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodaid.delivery.DeliveryPlan)
      grpc.foodaid.Deliver.DeliveryPlanOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foodaid.Deliver.FoodaidImpl.internal_static_foodaid_delivery_DeliveryPlan_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foodaid.Deliver.FoodaidImpl.internal_static_foodaid_delivery_DeliveryPlan_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foodaid.Deliver.DeliveryPlan.class, grpc.foodaid.Deliver.DeliveryPlan.Builder.class);
    }

    // Construct using grpc.foodaid.Deliver.DeliveryPlan.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalDeliveries_ = 0;

      deliveryAgent_ = "";

      route_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foodaid.Deliver.FoodaidImpl.internal_static_foodaid_delivery_DeliveryPlan_descriptor;
    }

    @java.lang.Override
    public grpc.foodaid.Deliver.DeliveryPlan getDefaultInstanceForType() {
      return grpc.foodaid.Deliver.DeliveryPlan.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foodaid.Deliver.DeliveryPlan build() {
      grpc.foodaid.Deliver.DeliveryPlan result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foodaid.Deliver.DeliveryPlan buildPartial() {
      grpc.foodaid.Deliver.DeliveryPlan result = new grpc.foodaid.Deliver.DeliveryPlan(this);
      int from_bitField0_ = bitField0_;
      result.totalDeliveries_ = totalDeliveries_;
      result.deliveryAgent_ = deliveryAgent_;
      if (((bitField0_ & 0x00000001) != 0)) {
        route_ = route_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.route_ = route_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foodaid.Deliver.DeliveryPlan) {
        return mergeFrom((grpc.foodaid.Deliver.DeliveryPlan)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foodaid.Deliver.DeliveryPlan other) {
      if (other == grpc.foodaid.Deliver.DeliveryPlan.getDefaultInstance()) return this;
      if (other.getTotalDeliveries() != 0) {
        setTotalDeliveries(other.getTotalDeliveries());
      }
      if (!other.getDeliveryAgent().isEmpty()) {
        deliveryAgent_ = other.deliveryAgent_;
        onChanged();
      }
      if (!other.route_.isEmpty()) {
        if (route_.isEmpty()) {
          route_ = other.route_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRouteIsMutable();
          route_.addAll(other.route_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foodaid.Deliver.DeliveryPlan parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foodaid.Deliver.DeliveryPlan) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int totalDeliveries_ ;
    /**
     * <pre>
     * count of orders
     * </pre>
     *
     * <code>int32 total_deliveries = 1;</code>
     * @return The totalDeliveries.
     */
    @java.lang.Override
    public int getTotalDeliveries() {
      return totalDeliveries_;
    }
    /**
     * <pre>
     * count of orders
     * </pre>
     *
     * <code>int32 total_deliveries = 1;</code>
     * @param value The totalDeliveries to set.
     * @return This builder for chaining.
     */
    public Builder setTotalDeliveries(int value) {
      
      totalDeliveries_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * count of orders
     * </pre>
     *
     * <code>int32 total_deliveries = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalDeliveries() {
      
      totalDeliveries_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deliveryAgent_ = "";
    /**
     * <pre>
     * assigned agent
     * </pre>
     *
     * <code>string delivery_agent = 2;</code>
     * @return The deliveryAgent.
     */
    public java.lang.String getDeliveryAgent() {
      java.lang.Object ref = deliveryAgent_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deliveryAgent_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * assigned agent
     * </pre>
     *
     * <code>string delivery_agent = 2;</code>
     * @return The bytes for deliveryAgent.
     */
    public com.google.protobuf.ByteString
        getDeliveryAgentBytes() {
      java.lang.Object ref = deliveryAgent_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * assigned agent
     * </pre>
     *
     * <code>string delivery_agent = 2;</code>
     * @param value The deliveryAgent to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryAgent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deliveryAgent_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * assigned agent
     * </pre>
     *
     * <code>string delivery_agent = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryAgent() {
      
      deliveryAgent_ = getDefaultInstance().getDeliveryAgent();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * assigned agent
     * </pre>
     *
     * <code>string delivery_agent = 2;</code>
     * @param value The bytes for deliveryAgent to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryAgentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deliveryAgent_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList route_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRouteIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        route_ = new com.google.protobuf.LazyStringArrayList(route_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @return A list containing the route.
     */
    public com.google.protobuf.ProtocolStringList
        getRouteList() {
      return route_.getUnmodifiableView();
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @return The count of route.
     */
    public int getRouteCount() {
      return route_.size();
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param index The index of the element to return.
     * @return The route at the given index.
     */
    public java.lang.String getRoute(int index) {
      return route_.get(index);
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the route at the given index.
     */
    public com.google.protobuf.ByteString
        getRouteBytes(int index) {
      return route_.getByteString(index);
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param index The index to set the value at.
     * @param value The route to set.
     * @return This builder for chaining.
     */
    public Builder setRoute(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRouteIsMutable();
      route_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param value The route to add.
     * @return This builder for chaining.
     */
    public Builder addRoute(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRouteIsMutable();
      route_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param values The route to add.
     * @return This builder for chaining.
     */
    public Builder addAllRoute(
        java.lang.Iterable<java.lang.String> values) {
      ensureRouteIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, route_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoute() {
      route_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered list of addresses
     * </pre>
     *
     * <code>repeated string route = 3;</code>
     * @param value The bytes of the route to add.
     * @return This builder for chaining.
     */
    public Builder addRouteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRouteIsMutable();
      route_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodaid.delivery.DeliveryPlan)
  }

  // @@protoc_insertion_point(class_scope:foodaid.delivery.DeliveryPlan)
  private static final grpc.foodaid.Deliver.DeliveryPlan DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foodaid.Deliver.DeliveryPlan();
  }

  public static grpc.foodaid.Deliver.DeliveryPlan getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeliveryPlan>
      PARSER = new com.google.protobuf.AbstractParser<DeliveryPlan>() {
    @java.lang.Override
    public DeliveryPlan parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeliveryPlan(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeliveryPlan> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeliveryPlan> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foodaid.Deliver.DeliveryPlan getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

