// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2FoodInsService.proto

package grpc.foodaid.Order;

/**
 * <pre>
 * Request a food order
 * </pre>
 *
 * Protobuf type {@code foodaid.order.OrderRequest}
 */
public final class OrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodaid.order.OrderRequest)
    OrderRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OrderRequest.newBuilder() to construct.
  private OrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OrderRequest() {
    recipient_ = "";
    foodType_ = "";
    deliveryAddress_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new OrderRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            recipient_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            foodType_ = s;
            break;
          }
          case 32: {

            quantity_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            deliveryAddress_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foodaid.Order.OrderImpl.internal_static_foodaid_order_OrderRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foodaid.Order.OrderImpl.internal_static_foodaid_order_OrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foodaid.Order.OrderRequest.class, grpc.foodaid.Order.OrderRequest.Builder.class);
  }

  public static final int RECIPIENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object recipient_;
  /**
   * <pre>
   *int32 order_id = 1;          // unique order identifier
   * </pre>
   *
   * <code>string recipient = 2;</code>
   * @return The recipient.
   */
  @java.lang.Override
  public java.lang.String getRecipient() {
    java.lang.Object ref = recipient_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      recipient_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *int32 order_id = 1;          // unique order identifier
   * </pre>
   *
   * <code>string recipient = 2;</code>
   * @return The bytes for recipient.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRecipientBytes() {
    java.lang.Object ref = recipient_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      recipient_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FOOD_TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object foodType_;
  /**
   * <pre>
   * ordered type of food
   * </pre>
   *
   * <code>string food_type = 3;</code>
   * @return The foodType.
   */
  @java.lang.Override
  public java.lang.String getFoodType() {
    java.lang.Object ref = foodType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foodType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ordered type of food
   * </pre>
   *
   * <code>string food_type = 3;</code>
   * @return The bytes for foodType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodTypeBytes() {
    java.lang.Object ref = foodType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foodType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FIELD_NUMBER = 4;
  private int quantity_;
  /**
   * <pre>
   * quantity requested
   * </pre>
   *
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  @java.lang.Override
  public int getQuantity() {
    return quantity_;
  }

  public static final int DELIVERY_ADDRESS_FIELD_NUMBER = 5;
  private volatile java.lang.Object deliveryAddress_;
  /**
   * <pre>
   * delivery address
   * </pre>
   *
   * <code>string delivery_address = 5;</code>
   * @return The deliveryAddress.
   */
  @java.lang.Override
  public java.lang.String getDeliveryAddress() {
    java.lang.Object ref = deliveryAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deliveryAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * delivery address
   * </pre>
   *
   * <code>string delivery_address = 5;</code>
   * @return The bytes for deliveryAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeliveryAddressBytes() {
    java.lang.Object ref = deliveryAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deliveryAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipient_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recipient_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, foodType_);
    }
    if (quantity_ != 0) {
      output.writeInt32(4, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deliveryAddress_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deliveryAddress_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(recipient_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recipient_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, foodType_);
    }
    if (quantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, quantity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deliveryAddress_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deliveryAddress_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foodaid.Order.OrderRequest)) {
      return super.equals(obj);
    }
    grpc.foodaid.Order.OrderRequest other = (grpc.foodaid.Order.OrderRequest) obj;

    if (!getRecipient()
        .equals(other.getRecipient())) return false;
    if (!getFoodType()
        .equals(other.getFoodType())) return false;
    if (getQuantity()
        != other.getQuantity()) return false;
    if (!getDeliveryAddress()
        .equals(other.getDeliveryAddress())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RECIPIENT_FIELD_NUMBER;
    hash = (53 * hash) + getRecipient().hashCode();
    hash = (37 * hash) + FOOD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFoodType().hashCode();
    hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + getQuantity();
    hash = (37 * hash) + DELIVERY_ADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getDeliveryAddress().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foodaid.Order.OrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Order.OrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Order.OrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Order.OrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foodaid.Order.OrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request a food order
   * </pre>
   *
   * Protobuf type {@code foodaid.order.OrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodaid.order.OrderRequest)
      grpc.foodaid.Order.OrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foodaid.Order.OrderImpl.internal_static_foodaid_order_OrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foodaid.Order.OrderImpl.internal_static_foodaid_order_OrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foodaid.Order.OrderRequest.class, grpc.foodaid.Order.OrderRequest.Builder.class);
    }

    // Construct using grpc.foodaid.Order.OrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      recipient_ = "";

      foodType_ = "";

      quantity_ = 0;

      deliveryAddress_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foodaid.Order.OrderImpl.internal_static_foodaid_order_OrderRequest_descriptor;
    }

    @java.lang.Override
    public grpc.foodaid.Order.OrderRequest getDefaultInstanceForType() {
      return grpc.foodaid.Order.OrderRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foodaid.Order.OrderRequest build() {
      grpc.foodaid.Order.OrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foodaid.Order.OrderRequest buildPartial() {
      grpc.foodaid.Order.OrderRequest result = new grpc.foodaid.Order.OrderRequest(this);
      result.recipient_ = recipient_;
      result.foodType_ = foodType_;
      result.quantity_ = quantity_;
      result.deliveryAddress_ = deliveryAddress_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foodaid.Order.OrderRequest) {
        return mergeFrom((grpc.foodaid.Order.OrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foodaid.Order.OrderRequest other) {
      if (other == grpc.foodaid.Order.OrderRequest.getDefaultInstance()) return this;
      if (!other.getRecipient().isEmpty()) {
        recipient_ = other.recipient_;
        onChanged();
      }
      if (!other.getFoodType().isEmpty()) {
        foodType_ = other.foodType_;
        onChanged();
      }
      if (other.getQuantity() != 0) {
        setQuantity(other.getQuantity());
      }
      if (!other.getDeliveryAddress().isEmpty()) {
        deliveryAddress_ = other.deliveryAddress_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foodaid.Order.OrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foodaid.Order.OrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object recipient_ = "";
    /**
     * <pre>
     *int32 order_id = 1;          // unique order identifier
     * </pre>
     *
     * <code>string recipient = 2;</code>
     * @return The recipient.
     */
    public java.lang.String getRecipient() {
      java.lang.Object ref = recipient_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recipient_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *int32 order_id = 1;          // unique order identifier
     * </pre>
     *
     * <code>string recipient = 2;</code>
     * @return The bytes for recipient.
     */
    public com.google.protobuf.ByteString
        getRecipientBytes() {
      java.lang.Object ref = recipient_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recipient_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *int32 order_id = 1;          // unique order identifier
     * </pre>
     *
     * <code>string recipient = 2;</code>
     * @param value The recipient to set.
     * @return This builder for chaining.
     */
    public Builder setRecipient(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      recipient_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *int32 order_id = 1;          // unique order identifier
     * </pre>
     *
     * <code>string recipient = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRecipient() {
      
      recipient_ = getDefaultInstance().getRecipient();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *int32 order_id = 1;          // unique order identifier
     * </pre>
     *
     * <code>string recipient = 2;</code>
     * @param value The bytes for recipient to set.
     * @return This builder for chaining.
     */
    public Builder setRecipientBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      recipient_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object foodType_ = "";
    /**
     * <pre>
     * ordered type of food
     * </pre>
     *
     * <code>string food_type = 3;</code>
     * @return The foodType.
     */
    public java.lang.String getFoodType() {
      java.lang.Object ref = foodType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ordered type of food
     * </pre>
     *
     * <code>string food_type = 3;</code>
     * @return The bytes for foodType.
     */
    public com.google.protobuf.ByteString
        getFoodTypeBytes() {
      java.lang.Object ref = foodType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ordered type of food
     * </pre>
     *
     * <code>string food_type = 3;</code>
     * @param value The foodType to set.
     * @return This builder for chaining.
     */
    public Builder setFoodType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      foodType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered type of food
     * </pre>
     *
     * <code>string food_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodType() {
      
      foodType_ = getDefaultInstance().getFoodType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ordered type of food
     * </pre>
     *
     * <code>string food_type = 3;</code>
     * @param value The bytes for foodType to set.
     * @return This builder for chaining.
     */
    public Builder setFoodTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      foodType_ = value;
      onChanged();
      return this;
    }

    private int quantity_ ;
    /**
     * <pre>
     * quantity requested
     * </pre>
     *
     * <code>int32 quantity = 4;</code>
     * @return The quantity.
     */
    @java.lang.Override
    public int getQuantity() {
      return quantity_;
    }
    /**
     * <pre>
     * quantity requested
     * </pre>
     *
     * <code>int32 quantity = 4;</code>
     * @param value The quantity to set.
     * @return This builder for chaining.
     */
    public Builder setQuantity(int value) {
      
      quantity_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * quantity requested
     * </pre>
     *
     * <code>int32 quantity = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantity() {
      
      quantity_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deliveryAddress_ = "";
    /**
     * <pre>
     * delivery address
     * </pre>
     *
     * <code>string delivery_address = 5;</code>
     * @return The deliveryAddress.
     */
    public java.lang.String getDeliveryAddress() {
      java.lang.Object ref = deliveryAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deliveryAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * delivery address
     * </pre>
     *
     * <code>string delivery_address = 5;</code>
     * @return The bytes for deliveryAddress.
     */
    public com.google.protobuf.ByteString
        getDeliveryAddressBytes() {
      java.lang.Object ref = deliveryAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deliveryAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * delivery address
     * </pre>
     *
     * <code>string delivery_address = 5;</code>
     * @param value The deliveryAddress to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deliveryAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * delivery address
     * </pre>
     *
     * <code>string delivery_address = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeliveryAddress() {
      
      deliveryAddress_ = getDefaultInstance().getDeliveryAddress();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * delivery address
     * </pre>
     *
     * <code>string delivery_address = 5;</code>
     * @param value The bytes for deliveryAddress to set.
     * @return This builder for chaining.
     */
    public Builder setDeliveryAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deliveryAddress_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodaid.order.OrderRequest)
  }

  // @@protoc_insertion_point(class_scope:foodaid.order.OrderRequest)
  private static final grpc.foodaid.Order.OrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foodaid.Order.OrderRequest();
  }

  public static grpc.foodaid.Order.OrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<OrderRequest>() {
    @java.lang.Override
    public OrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OrderRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foodaid.Order.OrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

