// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2FoodInsService.proto

// Protobuf Java Version: 3.25.3
package grpc.foodaid.Order;

public interface OrderStatusUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.order.OrderStatusUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * order identifier
   * </pre>
   *
   * <code>string order_id = 1;</code>
   * @return The orderId.
   */
  java.lang.String getOrderId();
  /**
   * <pre>
   * order identifier
   * </pre>
   *
   * <code>string order_id = 1;</code>
   * @return The bytes for orderId.
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <pre>
   * PREPAIRING,READY_TO_SHIP, SHIPPED, DELIVERED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * PREPAIRING,READY_TO_SHIP, SHIPPED, DELIVERED
   * </pre>
   *
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
