// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2FoodInsService.proto

package grpc.foodaid.Order;

public final class OrderImpl {
  private OrderImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_order_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_order_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_order_OrderConfirmation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_order_OrderConfirmation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_order_OrderStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_order_OrderStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_order_OrderStatusUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_order_OrderStatusUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026S2FoodInsService.proto\022\rfoodaid.order\"" +
      "`\n\014OrderRequest\022\021\n\trecipient\030\002 \001(\t\022\021\n\tfo" +
      "od_type\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\005\022\030\n\020deliv" +
      "ery_address\030\005 \001(\t\"I\n\021OrderConfirmation\022\020" +
      "\n\010order_id\030\001 \001(\t\022\021\n\tconfirmed\030\002 \001(\010\022\017\n\007m" +
      "essage\030\003 \001(\t\"&\n\022OrderStatusRequest\022\020\n\010or" +
      "der_id\030\001 \001(\t\"5\n\021OrderStatusUpdate\022\020\n\010ord" +
      "er_id\030\001 \001(\t\022\016\n\006status\030\002 \001(\t2\270\001\n\014OrderSer" +
      "vice\022K\n\nPlaceOrder\022\033.foodaid.order.Order" +
      "Request\032 .foodaid.order.OrderConfirmatio" +
      "n\022[\n\022StreamOrderUpdates\022!.foodaid.order." +
      "OrderStatusRequest\032 .foodaid.order.Order" +
      "StatusUpdate0\001B!\n\022grpc.foodaid.OrderB\tOr" +
      "derImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodaid_order_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodaid_order_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_order_OrderRequest_descriptor,
        new java.lang.String[] { "Recipient", "FoodType", "Quantity", "DeliveryAddress", });
    internal_static_foodaid_order_OrderConfirmation_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foodaid_order_OrderConfirmation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_order_OrderConfirmation_descriptor,
        new java.lang.String[] { "OrderId", "Confirmed", "Message", });
    internal_static_foodaid_order_OrderStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_foodaid_order_OrderStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_order_OrderStatusRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_foodaid_order_OrderStatusUpdate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_foodaid_order_OrderStatusUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_order_OrderStatusUpdate_descriptor,
        new java.lang.String[] { "OrderId", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
