// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2FoodInsService.proto

package grpc.foodaid.Order;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.order.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *int32 order_id = 1;          // unique order identifier
   * </pre>
   *
   * <code>string recipient = 2;</code>
   * @return The recipient.
   */
  java.lang.String getRecipient();
  /**
   * <pre>
   *int32 order_id = 1;          // unique order identifier
   * </pre>
   *
   * <code>string recipient = 2;</code>
   * @return The bytes for recipient.
   */
  com.google.protobuf.ByteString
      getRecipientBytes();

  /**
   * <pre>
   * ordered type of food
   * </pre>
   *
   * <code>string food_type = 3;</code>
   * @return The foodType.
   */
  java.lang.String getFoodType();
  /**
   * <pre>
   * ordered type of food
   * </pre>
   *
   * <code>string food_type = 3;</code>
   * @return The bytes for foodType.
   */
  com.google.protobuf.ByteString
      getFoodTypeBytes();

  /**
   * <pre>
   * quantity requested
   * </pre>
   *
   * <code>int32 quantity = 4;</code>
   * @return The quantity.
   */
  int getQuantity();

  /**
   * <pre>
   * delivery address
   * </pre>
   *
   * <code>string delivery_address = 5;</code>
   * @return The deliveryAddress.
   */
  java.lang.String getDeliveryAddress();
  /**
   * <pre>
   * delivery address
   * </pre>
   *
   * <code>string delivery_address = 5;</code>
   * @return The bytes for deliveryAddress.
   */
  com.google.protobuf.ByteString
      getDeliveryAddressBytes();
}
