// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/SurplusService.proto
// Protobuf Java Version: 4.31.1

package grpc.foodaid.surplus;

@com.google.protobuf.Generated
public final class FoodaidImpl {
  private FoodaidImpl() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      FoodaidImpl.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_Surplus_SurplusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_foodaid_Surplus_SurplusAcknowledge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/proto/SurplusService.proto\022\017f" +
      "oodaid.Surplus\"\201\001\n\016SurplusRequest\022\n\n\002id\030" +
      "\001 \001(\005\022\021\n\tfood_type\030\002 \001(\t\022\025\n\rquantity_foo" +
      "d\030\003 \001(\005\022\031\n\021nutritional_grade\030\004 \001(\005\022\020\n\010lo" +
      "cation\030\005 \001(\t\022\014\n\004depo\030\006 \001(\005\"7\n\022SurplusAck" +
      "nowledge\022\020\n\010accepted\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t2f\n\rSurpluService\022U\n\rSurplusRecord\022\037." +
      "foodaid.Surplus.SurplusRequest\032#.foodaid" +
      ".Surplus.SurplusAcknowledgeB%\n\024grpc.food" +
      "aid.surplusB\013FoodaidImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodaid_Surplus_SurplusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_foodaid_Surplus_SurplusRequest_descriptor,
        new java.lang.String[] { "Id", "FoodType", "QuantityFood", "NutritionalGrade", "Location", "Depo", });
    internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foodaid_Surplus_SurplusAcknowledge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor,
        new java.lang.String[] { "Accepted", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
