// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/proto/SurplusService.proto
// Protobuf Java Version: 4.31.1

package grpc.foodaid.surplus;

@com.google.protobuf.Generated
public interface SurplusAcknowledgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.Surplus.SurplusAcknowledge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true if recorded
   * </pre>
   *
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <pre>
   * Surplus registered
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Surplus registered
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
