// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1SurplusService.proto

package grpc.foodaid.Surplus;

public interface SurplusAcknowledgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.Surplus.SurplusAcknowledge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true if recorded
   * </pre>
   *
   * <code>bool accept = 1;</code>
   * @return The accept.
   */
  boolean getAccept();

  /**
   * <pre>
   * Surplus registered
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Surplus registered
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
