// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1SurplusService.proto

package grpc.foodaid.Surplus;

public final class SurplusImpl {
  private SurplusImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_Surplus_SurplusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_Surplus_SurplusAcknowledge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026S1SurplusService.proto\022\017foodaid.Surplu" +
      "s\"u\n\016SurplusRequest\022\021\n\tfood_type\030\002 \001(\t\022\025" +
      "\n\rquantity_food\030\003 \001(\005\022\031\n\021nutritional_gra" +
      "de\030\004 \001(\005\022\020\n\010location\030\005 \001(\t\022\014\n\004depo\030\006 \001(\005" +
      "\"5\n\022SurplusAcknowledge\022\016\n\006accept\030\001 \001(\010\022\017" +
      "\n\007message\030\002 \001(\t2g\n\016SurplusService\022U\n\rSur" +
      "plusRecord\022\037.foodaid.Surplus.SurplusRequ" +
      "est\032#.foodaid.Surplus.SurplusAcknowledge" +
      "B%\n\024grpc.foodaid.SurplusB\013SurplusImplP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodaid_Surplus_SurplusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_Surplus_SurplusRequest_descriptor,
        new java.lang.String[] { "FoodType", "QuantityFood", "NutritionalGrade", "Location", "Depo", });
    internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foodaid_Surplus_SurplusAcknowledge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_Surplus_SurplusAcknowledge_descriptor,
        new java.lang.String[] { "Accept", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
