// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S1SurplusService.proto

package grpc.foodaid.Surplus;

/**
 * Protobuf type {@code foodaid.Surplus.SurplusRequest}
 */
public final class SurplusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodaid.Surplus.SurplusRequest)
    SurplusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SurplusRequest.newBuilder() to construct.
  private SurplusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SurplusRequest() {
    foodType_ = "";
    location_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SurplusRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SurplusRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            foodType_ = s;
            break;
          }
          case 24: {

            quantityFood_ = input.readInt32();
            break;
          }
          case 32: {

            nutritionalGrade_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            location_ = s;
            break;
          }
          case 48: {

            depo_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foodaid.Surplus.SurplusImpl.internal_static_foodaid_Surplus_SurplusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foodaid.Surplus.SurplusImpl.internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foodaid.Surplus.SurplusRequest.class, grpc.foodaid.Surplus.SurplusRequest.Builder.class);
  }

  public static final int FOOD_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object foodType_;
  /**
   * <pre>
   *int32 id = 1;                // unique identifier
   * </pre>
   *
   * <code>string food_type = 2;</code>
   * @return The foodType.
   */
  @java.lang.Override
  public java.lang.String getFoodType() {
    java.lang.Object ref = foodType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foodType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *int32 id = 1;                // unique identifier
   * </pre>
   *
   * <code>string food_type = 2;</code>
   * @return The bytes for foodType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoodTypeBytes() {
    java.lang.Object ref = foodType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foodType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUANTITY_FOOD_FIELD_NUMBER = 3;
  private int quantityFood_;
  /**
   * <pre>
   * quantity of food
   * </pre>
   *
   * <code>int32 quantity_food = 3;</code>
   * @return The quantityFood.
   */
  @java.lang.Override
  public int getQuantityFood() {
    return quantityFood_;
  }

  public static final int NUTRITIONAL_GRADE_FIELD_NUMBER = 4;
  private int nutritionalGrade_;
  /**
   * <pre>
   * nutritional rate for food type i.e. 1-10
   * </pre>
   *
   * <code>int32 nutritional_grade = 4;</code>
   * @return The nutritionalGrade.
   */
  @java.lang.Override
  public int getNutritionalGrade() {
    return nutritionalGrade_;
  }

  public static final int LOCATION_FIELD_NUMBER = 5;
  private volatile java.lang.Object location_;
  /**
   * <pre>
   * location of surplus
   * </pre>
   *
   * <code>string location = 5;</code>
   * @return The location.
   */
  @java.lang.Override
  public java.lang.String getLocation() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      location_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * location of surplus
   * </pre>
   *
   * <code>string location = 5;</code>
   * @return The bytes for location.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLocationBytes() {
    java.lang.Object ref = location_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      location_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPO_FIELD_NUMBER = 6;
  private int depo_;
  /**
   * <pre>
   * depo ID for where surplus is stored
   * </pre>
   *
   * <code>int32 depo = 6;</code>
   * @return The depo.
   */
  @java.lang.Override
  public int getDepo() {
    return depo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, foodType_);
    }
    if (quantityFood_ != 0) {
      output.writeInt32(3, quantityFood_);
    }
    if (nutritionalGrade_ != 0) {
      output.writeInt32(4, nutritionalGrade_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, location_);
    }
    if (depo_ != 0) {
      output.writeInt32(6, depo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(foodType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, foodType_);
    }
    if (quantityFood_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, quantityFood_);
    }
    if (nutritionalGrade_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, nutritionalGrade_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(location_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, location_);
    }
    if (depo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, depo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foodaid.Surplus.SurplusRequest)) {
      return super.equals(obj);
    }
    grpc.foodaid.Surplus.SurplusRequest other = (grpc.foodaid.Surplus.SurplusRequest) obj;

    if (!getFoodType()
        .equals(other.getFoodType())) return false;
    if (getQuantityFood()
        != other.getQuantityFood()) return false;
    if (getNutritionalGrade()
        != other.getNutritionalGrade()) return false;
    if (!getLocation()
        .equals(other.getLocation())) return false;
    if (getDepo()
        != other.getDepo()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FOOD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getFoodType().hashCode();
    hash = (37 * hash) + QUANTITY_FOOD_FIELD_NUMBER;
    hash = (53 * hash) + getQuantityFood();
    hash = (37 * hash) + NUTRITIONAL_GRADE_FIELD_NUMBER;
    hash = (53 * hash) + getNutritionalGrade();
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation().hashCode();
    hash = (37 * hash) + DEPO_FIELD_NUMBER;
    hash = (53 * hash) + getDepo();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Surplus.SurplusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foodaid.Surplus.SurplusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodaid.Surplus.SurplusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodaid.Surplus.SurplusRequest)
      grpc.foodaid.Surplus.SurplusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foodaid.Surplus.SurplusImpl.internal_static_foodaid_Surplus_SurplusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foodaid.Surplus.SurplusImpl.internal_static_foodaid_Surplus_SurplusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foodaid.Surplus.SurplusRequest.class, grpc.foodaid.Surplus.SurplusRequest.Builder.class);
    }

    // Construct using grpc.foodaid.Surplus.SurplusRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      foodType_ = "";

      quantityFood_ = 0;

      nutritionalGrade_ = 0;

      location_ = "";

      depo_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foodaid.Surplus.SurplusImpl.internal_static_foodaid_Surplus_SurplusRequest_descriptor;
    }

    @java.lang.Override
    public grpc.foodaid.Surplus.SurplusRequest getDefaultInstanceForType() {
      return grpc.foodaid.Surplus.SurplusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foodaid.Surplus.SurplusRequest build() {
      grpc.foodaid.Surplus.SurplusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foodaid.Surplus.SurplusRequest buildPartial() {
      grpc.foodaid.Surplus.SurplusRequest result = new grpc.foodaid.Surplus.SurplusRequest(this);
      result.foodType_ = foodType_;
      result.quantityFood_ = quantityFood_;
      result.nutritionalGrade_ = nutritionalGrade_;
      result.location_ = location_;
      result.depo_ = depo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foodaid.Surplus.SurplusRequest) {
        return mergeFrom((grpc.foodaid.Surplus.SurplusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foodaid.Surplus.SurplusRequest other) {
      if (other == grpc.foodaid.Surplus.SurplusRequest.getDefaultInstance()) return this;
      if (!other.getFoodType().isEmpty()) {
        foodType_ = other.foodType_;
        onChanged();
      }
      if (other.getQuantityFood() != 0) {
        setQuantityFood(other.getQuantityFood());
      }
      if (other.getNutritionalGrade() != 0) {
        setNutritionalGrade(other.getNutritionalGrade());
      }
      if (!other.getLocation().isEmpty()) {
        location_ = other.location_;
        onChanged();
      }
      if (other.getDepo() != 0) {
        setDepo(other.getDepo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foodaid.Surplus.SurplusRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foodaid.Surplus.SurplusRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object foodType_ = "";
    /**
     * <pre>
     *int32 id = 1;                // unique identifier
     * </pre>
     *
     * <code>string food_type = 2;</code>
     * @return The foodType.
     */
    public java.lang.String getFoodType() {
      java.lang.Object ref = foodType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foodType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *int32 id = 1;                // unique identifier
     * </pre>
     *
     * <code>string food_type = 2;</code>
     * @return The bytes for foodType.
     */
    public com.google.protobuf.ByteString
        getFoodTypeBytes() {
      java.lang.Object ref = foodType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foodType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *int32 id = 1;                // unique identifier
     * </pre>
     *
     * <code>string food_type = 2;</code>
     * @param value The foodType to set.
     * @return This builder for chaining.
     */
    public Builder setFoodType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      foodType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *int32 id = 1;                // unique identifier
     * </pre>
     *
     * <code>string food_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoodType() {
      
      foodType_ = getDefaultInstance().getFoodType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *int32 id = 1;                // unique identifier
     * </pre>
     *
     * <code>string food_type = 2;</code>
     * @param value The bytes for foodType to set.
     * @return This builder for chaining.
     */
    public Builder setFoodTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      foodType_ = value;
      onChanged();
      return this;
    }

    private int quantityFood_ ;
    /**
     * <pre>
     * quantity of food
     * </pre>
     *
     * <code>int32 quantity_food = 3;</code>
     * @return The quantityFood.
     */
    @java.lang.Override
    public int getQuantityFood() {
      return quantityFood_;
    }
    /**
     * <pre>
     * quantity of food
     * </pre>
     *
     * <code>int32 quantity_food = 3;</code>
     * @param value The quantityFood to set.
     * @return This builder for chaining.
     */
    public Builder setQuantityFood(int value) {
      
      quantityFood_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * quantity of food
     * </pre>
     *
     * <code>int32 quantity_food = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuantityFood() {
      
      quantityFood_ = 0;
      onChanged();
      return this;
    }

    private int nutritionalGrade_ ;
    /**
     * <pre>
     * nutritional rate for food type i.e. 1-10
     * </pre>
     *
     * <code>int32 nutritional_grade = 4;</code>
     * @return The nutritionalGrade.
     */
    @java.lang.Override
    public int getNutritionalGrade() {
      return nutritionalGrade_;
    }
    /**
     * <pre>
     * nutritional rate for food type i.e. 1-10
     * </pre>
     *
     * <code>int32 nutritional_grade = 4;</code>
     * @param value The nutritionalGrade to set.
     * @return This builder for chaining.
     */
    public Builder setNutritionalGrade(int value) {
      
      nutritionalGrade_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * nutritional rate for food type i.e. 1-10
     * </pre>
     *
     * <code>int32 nutritional_grade = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNutritionalGrade() {
      
      nutritionalGrade_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object location_ = "";
    /**
     * <pre>
     * location of surplus
     * </pre>
     *
     * <code>string location = 5;</code>
     * @return The location.
     */
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * location of surplus
     * </pre>
     *
     * <code>string location = 5;</code>
     * @return The bytes for location.
     */
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * location of surplus
     * </pre>
     *
     * <code>string location = 5;</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      location_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * location of surplus
     * </pre>
     *
     * <code>string location = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      
      location_ = getDefaultInstance().getLocation();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * location of surplus
     * </pre>
     *
     * <code>string location = 5;</code>
     * @param value The bytes for location to set.
     * @return This builder for chaining.
     */
    public Builder setLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      location_ = value;
      onChanged();
      return this;
    }

    private int depo_ ;
    /**
     * <pre>
     * depo ID for where surplus is stored
     * </pre>
     *
     * <code>int32 depo = 6;</code>
     * @return The depo.
     */
    @java.lang.Override
    public int getDepo() {
      return depo_;
    }
    /**
     * <pre>
     * depo ID for where surplus is stored
     * </pre>
     *
     * <code>int32 depo = 6;</code>
     * @param value The depo to set.
     * @return This builder for chaining.
     */
    public Builder setDepo(int value) {
      
      depo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * depo ID for where surplus is stored
     * </pre>
     *
     * <code>int32 depo = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDepo() {
      
      depo_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodaid.Surplus.SurplusRequest)
  }

  // @@protoc_insertion_point(class_scope:foodaid.Surplus.SurplusRequest)
  private static final grpc.foodaid.Surplus.SurplusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foodaid.Surplus.SurplusRequest();
  }

  public static grpc.foodaid.Surplus.SurplusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SurplusRequest>
      PARSER = new com.google.protobuf.AbstractParser<SurplusRequest>() {
    @java.lang.Override
    public SurplusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SurplusRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SurplusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SurplusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foodaid.Surplus.SurplusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

