// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.chat.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The senderName.
   */
  java.lang.String getSenderName();
  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The bytes for senderName.
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
