// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

public final class ChatImpl {
  private ChatImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_chat_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_chat_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_chat_ChatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_chat_ChatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023S4ChatService.proto\022\014foodaid.chat\"2\n\013C" +
      "hatRequest\022\022\n\nsenderName\030\001 \001(\t\022\017\n\007messag" +
      "e\030\002 \001(\t\";\n\014ChatResponse\022\022\n\nsenderName\030\001 " +
      "\001(\t\022\027\n\017responseMessage\030\002 \001(\t2T\n\013ChatServ" +
      "ice\022E\n\010LiveChat\022\031.foodaid.chat.ChatReque" +
      "st\032\032.foodaid.chat.ChatResponse(\0010\001B\037\n\021gr" +
      "pc.foodaid.ChatB\010ChatImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodaid_chat_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodaid_chat_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_chat_ChatRequest_descriptor,
        new java.lang.String[] { "SenderName", "Message", });
    internal_static_foodaid_chat_ChatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_foodaid_chat_ChatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_chat_ChatResponse_descriptor,
        new java.lang.String[] { "SenderName", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
