// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.chat.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * timestamp of message
   * </pre>
   *
   * <code>string dateTime = 1;</code>
   * @return The dateTime.
   */
  java.lang.String getDateTime();
  /**
   * <pre>
   * timestamp of message
   * </pre>
   *
   * <code>string dateTime = 1;</code>
   * @return The bytes for dateTime.
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();

  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
