// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

public interface ChatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:foodaid.chat.ChatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The senderName.
   */
  java.lang.String getSenderName();
  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The bytes for senderName.
   */
  com.google.protobuf.ByteString
      getSenderNameBytes();

  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The responseMessage.
   */
  java.lang.String getResponseMessage();
  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The bytes for responseMessage.
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();
}
