// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

/**
 * Protobuf type {@code foodaid.chat.ChatResponse}
 */
public final class ChatResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:foodaid.chat.ChatResponse)
    ChatResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatResponse.newBuilder() to construct.
  private ChatResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatResponse() {
    senderName_ = "";
    responseMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            senderName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            responseMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.foodaid.Chat.ChatImpl.internal_static_foodaid_chat_ChatResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.foodaid.Chat.ChatImpl.internal_static_foodaid_chat_ChatResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.foodaid.Chat.ChatResponse.class, grpc.foodaid.Chat.ChatResponse.Builder.class);
  }

  public static final int SENDERNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object senderName_;
  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The senderName.
   */
  @java.lang.Override
  public java.lang.String getSenderName() {
    java.lang.Object ref = senderName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * name of message sender
   * </pre>
   *
   * <code>string senderName = 1;</code>
   * @return The bytes for senderName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderNameBytes() {
    java.lang.Object ref = senderName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSEMESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object responseMessage_;
  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The responseMessage.
   */
  @java.lang.Override
  public java.lang.String getResponseMessage() {
    java.lang.Object ref = responseMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * chat message
   * </pre>
   *
   * <code>string responseMessage = 2;</code>
   * @return The bytes for responseMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResponseMessageBytes() {
    java.lang.Object ref = responseMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, senderName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseMessage_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(senderName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, senderName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseMessage_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.foodaid.Chat.ChatResponse)) {
      return super.equals(obj);
    }
    grpc.foodaid.Chat.ChatResponse other = (grpc.foodaid.Chat.ChatResponse) obj;

    if (!getSenderName()
        .equals(other.getSenderName())) return false;
    if (!getResponseMessage()
        .equals(other.getResponseMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSenderName().hashCode();
    hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Chat.ChatResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Chat.ChatResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.foodaid.Chat.ChatResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.foodaid.Chat.ChatResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code foodaid.chat.ChatResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:foodaid.chat.ChatResponse)
      grpc.foodaid.Chat.ChatResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.foodaid.Chat.ChatImpl.internal_static_foodaid_chat_ChatResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.foodaid.Chat.ChatImpl.internal_static_foodaid_chat_ChatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.foodaid.Chat.ChatResponse.class, grpc.foodaid.Chat.ChatResponse.Builder.class);
    }

    // Construct using grpc.foodaid.Chat.ChatResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      senderName_ = "";

      responseMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.foodaid.Chat.ChatImpl.internal_static_foodaid_chat_ChatResponse_descriptor;
    }

    @java.lang.Override
    public grpc.foodaid.Chat.ChatResponse getDefaultInstanceForType() {
      return grpc.foodaid.Chat.ChatResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.foodaid.Chat.ChatResponse build() {
      grpc.foodaid.Chat.ChatResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.foodaid.Chat.ChatResponse buildPartial() {
      grpc.foodaid.Chat.ChatResponse result = new grpc.foodaid.Chat.ChatResponse(this);
      result.senderName_ = senderName_;
      result.responseMessage_ = responseMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.foodaid.Chat.ChatResponse) {
        return mergeFrom((grpc.foodaid.Chat.ChatResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.foodaid.Chat.ChatResponse other) {
      if (other == grpc.foodaid.Chat.ChatResponse.getDefaultInstance()) return this;
      if (!other.getSenderName().isEmpty()) {
        senderName_ = other.senderName_;
        onChanged();
      }
      if (!other.getResponseMessage().isEmpty()) {
        responseMessage_ = other.responseMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.foodaid.Chat.ChatResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.foodaid.Chat.ChatResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object senderName_ = "";
    /**
     * <pre>
     * name of message sender
     * </pre>
     *
     * <code>string senderName = 1;</code>
     * @return The senderName.
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * name of message sender
     * </pre>
     *
     * <code>string senderName = 1;</code>
     * @return The bytes for senderName.
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * name of message sender
     * </pre>
     *
     * <code>string senderName = 1;</code>
     * @param value The senderName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      senderName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of message sender
     * </pre>
     *
     * <code>string senderName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderName() {
      
      senderName_ = getDefaultInstance().getSenderName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * name of message sender
     * </pre>
     *
     * <code>string senderName = 1;</code>
     * @param value The bytes for senderName to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      senderName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object responseMessage_ = "";
    /**
     * <pre>
     * chat message
     * </pre>
     *
     * <code>string responseMessage = 2;</code>
     * @return The responseMessage.
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * chat message
     * </pre>
     *
     * <code>string responseMessage = 2;</code>
     * @return The bytes for responseMessage.
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * chat message
     * </pre>
     *
     * <code>string responseMessage = 2;</code>
     * @param value The responseMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResponseMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responseMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * chat message
     * </pre>
     *
     * <code>string responseMessage = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseMessage() {
      
      responseMessage_ = getDefaultInstance().getResponseMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * chat message
     * </pre>
     *
     * <code>string responseMessage = 2;</code>
     * @param value The bytes for responseMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responseMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:foodaid.chat.ChatResponse)
  }

  // @@protoc_insertion_point(class_scope:foodaid.chat.ChatResponse)
  private static final grpc.foodaid.Chat.ChatResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.foodaid.Chat.ChatResponse();
  }

  public static grpc.foodaid.Chat.ChatResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChatResponse>() {
    @java.lang.Override
    public ChatResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.foodaid.Chat.ChatResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

