// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S4ChatService.proto

package grpc.foodaid.Chat;

public final class ChatImpl {
  private ChatImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_foodaid_chat_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_foodaid_chat_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023S4ChatService.proto\022\014foodaid.chat\"1\n\013C" +
      "hatMessage\022\021\n\tsender_id\030\001 \001(\005\022\017\n\007message" +
      "\030\002 \001(\t2S\n\013ChatService\022D\n\010LiveChat\022\031.food" +
      "aid.chat.ChatMessage\032\031.foodaid.chat.Chat" +
      "Message(\0010\001B\037\n\021grpc.foodaid.ChatB\010ChatIm" +
      "plP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_foodaid_chat_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_foodaid_chat_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_foodaid_chat_ChatMessage_descriptor,
        new java.lang.String[] { "SenderId", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
